<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFbnIeTp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFbnIeTp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFbnIeTp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFbnIeTp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFbnIeTp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FbnIeTp',
    'container.build_id' => 'c8e01202',
    'container.build_time' => 1635087280,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFbnIeTp');
